base:
    seed: &seed 42
model:
    type: Llama
    path: model path
    torch_dtype: auto
quant:
    method: RTN
    weight:
        bit: 4
        symmetric: False
        granularity: per_group
        group_size: 128
save:
    save_trans: False
    save_path: ./save_w4a16