base:
    seed: &seed 42
model:
    type: model_type
    path: model path
    torch_dtype: auto
quant:
    method: RTN
    weight:
        bit: 4
        symmetric: True
        granularity: per_group
        group_size: 128
        int_range: [-8, 7]
        pack_mode: vllm_pack
eval:
    eval_pos: [fake_quant]
    name: wikitext2
    download: False
    path: eval data path
    bs: 1
    seq_len: 2048
    inference_per_block: False
    eval_token_consist: True
save:
    save_vllm: True
    save_path: /path/to/save_for_vllm_rtn/
