base:
    seed: &seed 42
model:
    type: Llama
    path: /mnt/nvme0/lvchengtao/pretrain_weights/llama2/llama2-7b
    torch_dtype: auto
eval:
    eval_pos: [pretrain, fake_quant]
    name: wikitext2
    download: False
    path: /mnt/nvme0/lvchengtao/dataset/llm_eval/wikitext2
    bs: 1
    seq_len: 2048
quant:
    method: RTN
    weight:
        bit: e5m2
        symmetric: True
        granularity: per_channel
    act:
        bit: e5m2
        symmetric: True
        granularity: per_token
save:
    save_trans: False
    save_path: ./save